spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mall?serverTimezone=Asia/Taipei&characterEncoding=utf-8
    username: arthur
    password: a15457788
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
logging:
  level:
    org.springframework.security: DEBUG
jwt:
  signing:
    key: secret
